spring:
  jpa:
    show-sql: true
    properties:
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.xml"

