spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: true
    properties:
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.xml"

server:
  port: 8081
