CREATE EXTENSION "uuid-ossp";

ALTER TABLE activity ALTER COLUMN id DROP IDENTITY;
ALTER TABLE activity ALTER COLUMN id SET DATA TYPE UUID USING (uuid_generate_v4());
ALTER TABLE activity ALTER COLUMN user_id SET DATA TYPE UUID USING (uuid_generate_v4());
ALTER TABLE activity ALTER COLUMN object_id SET DATA TYPE UUID USING (uuid_generate_v4());
ALTER TABLE users ADD COLUMN id_uuid UUID NULL DEFAULT uuid_generate_v4();
ALTER TABLE userprofiles ADD COLUMN id_uuid UUID NULL DEFAULT uuid_generate_v4();
ALTER TABLE userprofiles ADD COLUMN user_id_uuid UUID NULL DEFAULT uuid_generate_v4();
ALTER TABLE user_authorities ADD COLUMN user_id_uuid UUID NULL DEFAULT uuid_generate_v4();
ALTER TABLE follower_following ADD COLUMN follower_id_uuid UUID NULL DEFAULT uuid_generate_v4();
ALTER TABLE follower_following ADD COLUMN following_id_uuid UUID NULL DEFAULT uuid_generate_v4();
ALTER TABLE events ADD COLUMN id_uuid UUID NULL DEFAULT uuid_generate_v4();
ALTER TABLE events ADD COLUMN organizer_id_uuid UUID NULL DEFAULT uuid_generate_v4();
ALTER TABLE eventquestions ADD COLUMN id_uuid UUID NULL DEFAULT uuid_generate_v4();
ALTER TABLE eventquestions ADD COLUMN event_id_uuid UUID NULL DEFAULT uuid_generate_v4();
ALTER TABLE event_question_answers ADD COLUMN id_uuid UUID NULL DEFAULT uuid_generate_v4();
ALTER TABLE event_question_answers ADD COLUMN question_id_uuid UUID NULL DEFAULT uuid_generate_v4();
ALTER TABLE event_question_answers ADD COLUMN event_application_id_uuid UUID NULL DEFAULT uuid_generate_v4();
ALTER TABLE event_applications ADD COLUMN id_uuid UUID NULL DEFAULT uuid_generate_v4();
ALTER TABLE event_applications ADD COLUMN event_id_uuid UUID NULL DEFAULT uuid_generate_v4();
ALTER TABLE event_applications ADD COLUMN user_id_uuid UUID NULL DEFAULT uuid_generate_v4();

UPDATE userprofiles SET user_id_uuid = (SELECT id_uuid FROM users WHERE users.id = userprofiles.user_id);
UPDATE user_authorities SET user_id_uuid = (SELECT id_uuid FROM users WHERE users.id = user_authorities.user_id);
UPDATE follower_following SET follower_id_uuid = (SELECT id_uuid FROM users WHERE users.id = follower_following.follower_id);
UPDATE follower_following SET following_id_uuid = (SELECT id_uuid FROM users WHERE users.id = follower_following.following_id);
UPDATE events SET organizer_id_uuid = (SELECT id_uuid FROM users WHERE users.id = events.organizer_id);
UPDATE eventquestions SET event_id_uuid = (SELECT id_uuid FROM events WHERE events.id = eventquestions.event_id);
UPDATE event_question_answers SET question_id_uuid = (SELECT id_uuid FROM eventquestions WHERE eventquestions.id = event_question_answers.question_id);
UPDATE event_question_answers SET event_application_id_uuid = (SELECT id_uuid FROM event_applications WHERE event_applications.id = event_question_answers.event_application_id);
UPDATE event_applications SET event_id_uuid = (SELECT id_uuid FROM events WHERE events.id = event_applications.event_id);
UPDATE event_applications SET user_id_uuid = (SELECT id_uuid FROM users WHERE users.id = event_applications.user_id);

ALTER TABLE users DROP COLUMN id CASCADE;
ALTER TABLE userprofiles DROP COLUMN id CASCADE;
ALTER TABLE userprofiles DROP COLUMN user_id CASCADE;
ALTER TABLE user_authorities DROP COLUMN user_id CASCADE;
ALTER TABLE follower_following DROP COLUMN follower_id CASCADE;
ALTER TABLE follower_following DROP COLUMN following_id CASCADE;
ALTER TABLE events DROP COLUMN id CASCADE;
ALTER TABLE events DROP COLUMN organizer_id CASCADE;
ALTER TABLE eventquestions DROP COLUMN id CASCADE;
ALTER TABLE eventquestions DROP COLUMN event_id CASCADE;
ALTER TABLE event_question_answers DROP COLUMN id CASCADE;
ALTER TABLE event_question_answers DROP COLUMN question_id CASCADE;
ALTER TABLE event_question_answers DROP COLUMN event_application_id CASCADE;
ALTER TABLE event_applications DROP COLUMN id CASCADE;
ALTER TABLE event_applications DROP COLUMN event_id CASCADE;
ALTER TABLE event_applications DROP COLUMN user_id CASCADE;

ALTER TABLE users RENAME COLUMN id_uuid TO id;
ALTER TABLE userprofiles RENAME COLUMN id_uuid TO id;
ALTER TABLE userprofiles RENAME COLUMN user_id_uuid TO user_id;
ALTER TABLE user_authorities RENAME COLUMN user_id_uuid TO user_id;
ALTER TABLE follower_following RENAME COLUMN follower_id_uuid TO follower_id;
ALTER TABLE follower_following RENAME COLUMN following_id_uuid TO following_id;
ALTER TABLE events RENAME COLUMN id_uuid TO id;
ALTER TABLE events RENAME COLUMN organizer_id_uuid TO organizer_id;
ALTER TABLE eventquestions RENAME COLUMN id_uuid TO id;
ALTER TABLE eventquestions RENAME COLUMN event_id_uuid TO event_id;
ALTER TABLE event_question_answers RENAME COLUMN id_uuid TO id;
ALTER TABLE event_question_answers RENAME COLUMN question_id_uuid TO question_id;
ALTER TABLE event_question_answers RENAME COLUMN event_application_id_uuid TO event_application_id;
ALTER TABLE event_applications RENAME COLUMN id_uuid TO id;
ALTER TABLE event_applications RENAME COLUMN event_id_uuid TO event_id;
ALTER TABLE event_applications RENAME COLUMN user_id_uuid TO user_id;

ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE userprofiles ADD CONSTRAINT userprofiles_pkey PRIMARY KEY (id);
ALTER TABLE user_authorities ADD CONSTRAINT user_authorities_pkey PRIMARY KEY (user_id, authority_id);
ALTER TABLE follower_following ADD CONSTRAINT follower_following_pkey PRIMARY KEY (follower_id, following_id);
ALTER TABLE events ADD CONSTRAINT events_pkey PRIMARY KEY (id);
ALTER TABLE eventquestions ADD CONSTRAINT eventquestions_pkey PRIMARY KEY (id);
ALTER TABLE event_question_answers ADD CONSTRAINT event_question_answers_pkey PRIMARY KEY (id);
ALTER TABLE event_applications ADD CONSTRAINT event_applications_pkey PRIMARY KEY (id);

ALTER TABLE userprofiles ADD CONSTRAINT userprofiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE user_authorities ADD CONSTRAINT user_authorities_authority_id_fkey FOREIGN KEY (authority_id) REFERENCES authorities (id);
ALTER TABLE follower_following ADD CONSTRAINT follower_following_follower_id_fkey FOREIGN KEY (follower_id) REFERENCES users (id);
ALTER TABLE follower_following ADD CONSTRAINT follower_following_following_id_fkey FOREIGN KEY (following_id) REFERENCES users (id);
ALTER TABLE eventquestions ADD CONSTRAINT eventquestions_event_id_fkey FOREIGN KEY (event_id) REFERENCES events (id);
ALTER TABLE event_question_answers ADD CONSTRAINT event_question_answers_event_application_id_fkey FOREIGN KEY (event_application_id) REFERENCES event_applications (id);
ALTER TABLE event_question_answers ADD CONSTRAINT event_question_answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES eventquestions (id);
ALTER TABLE event_applications ADD CONSTRAINT event_applications_event_id_fkey FOREIGN KEY (event_id) REFERENCES events (id);
ALTER TABLE event_applications ADD CONSTRAINT event_applications_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE userprofiles ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE user_authorities ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE follower_following ALTER COLUMN follower_id SET NOT NULL;
ALTER TABLE follower_following ALTER COLUMN following_id SET NOT NULL;
ALTER TABLE eventquestions ALTER COLUMN event_id SET NOT NULL;
ALTER TABLE event_question_answers ALTER COLUMN event_application_id SET NOT NULL;
ALTER TABLE event_question_answers ALTER COLUMN question_id SET NOT NULL;
ALTER TABLE event_applications ALTER COLUMN event_id SET NOT NULL;
ALTER TABLE event_applications ALTER COLUMN user_id SET NOT NULL;